#!/usr/bin/env python3
#Name: Leonardo Pinto
#Function: Directory Creation

# Import libraries

import os

# Declaration of variables

### Read user input here into a variable

user_input = input("Enter the directory path: ")

# Declaration of functions

### Declare a function here

# Declaration of functions
def list_directories_and_files(testedir):
    for (root, dirs, files) in os.walk(testedir):
        # Add a print command here to print ==root==
        print("Root Directory:", root)
        # Add a print command here to print ==dirs==
        print("Subdirectories:", dirs)
        # Add a print command here to print ==files==
        print("Files:", files)

# Main

### Pass the variable into the function here
list_directories_and_files(user_input)
# End
